src/main/java/es/apba/oper/pcs/scp/dashboards/Beans/LoginBean.java
package es.apba.oper.pcs.scp.dashboards.Beans;

import es.apba.oper.pcs.scp.dashboards.Data.UserData;
import lombok.Getter;
import lombok.Setter;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;

import javax.annotation.ManagedBean;
import java.io.Serializable;

@ManagedBean
@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
@Getter
@Setter
public class LoginBean
{
	private UserData user;

	public String getUserHeader()
	{
		return user.getUsername() + "(" + user.getCompanyName() + ")" + (user.isAdmin() ? ". ADMIN" : ".");
	}
}

src/main/webapp/pages/completeView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <title>Complete View</title>
    <script name="jquery/jquery.js" library="primefaces"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@latest"></script>
    <script src="../resources/JavaScript/pie.js"></script>

    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>


    <style>

    #chart {
      max-width: 650px;
      margin: 35px auto;
    }


  </style>

    <script>
    // Replace Math.random() with a pseudo-random number generator to get reproducible results in e2e tests
    // Based on https://gist.github.com/blixt/f17b47c62508be59987b
    var _seed = 42;
    Math.random = function() {
      _seed = _seed * 16807 % 2147483647;
      return (_seed - 1) / 2147483646;
    };
    </script>
</h:head>

<style type="text/css">
    #chart {
      max-width: 650px;
      margin: 35px auto;
    }

    .value {
        font-weight: bold;
    }
    .ui-toggleswitch {
        vertical-align: bottom;
    }
    .ui-widget-header {
    background-color: #ffffff;
    background: white;
    color: #517DBA;
    text-align: center;
    border: 0px;
    }
    .ui-grid {
        border-radius: 40px;
        border-width: 2px;
        border-color: #5A658D;
    }

    </style>
<h:body>
    <h:form id="completeView">
        <h:panelGrid id="main" columns="2" style="margin-bottom:10px; width: 100%; align: center" cellpading="7">
            <h:panelGrid id="total" columns="7" cellpading="7">
                <h:outputText value="Total tickets:" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                <h:outputText value="#{generalDashboardViewBean.totalVehiclesAndPassengers}" style="font-weight:bold; display: block; width:100%; text-align:center; font-size: x-large;"/>
                <h:outputText value="desde" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-left:2em"/>
                <p:calendar value="#{generalDashboardViewBean.startTime}" pattern="dd/MM/yyyy HH:mm"></p:calendar>
                <h:outputText value="hasta" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-left:2em; padding-right:2em"/>
                <p:calendar value="#{generalDashboardViewBean.endTime}" pattern="dd/MM/yyyy HH:mm"></p:calendar>
                <p:commandButton id="Ajax" value="Submit" update="total, :completeView:issuingGraphic, :completeView:checkingGraphic, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets, :completeView:Filter" action="#{generalDashboardViewBean.onTotal()}" ajax="true"/>
            </h:panelGrid>
            <h:panelGrid style="margin-bottom:10px; width: 100%; text-align-last: end" cellpading="7">
                <h:outputText value="User: #{loginBean.userHeader}" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; margin-right: 50px" />
            </h:panelGrid>
        </h:panelGrid>

        <hr />

        <p:panelGrid columns="2" layout="grid" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
            <p:panel id="issuingGraphic" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <div id="GRAPHIC-ISSUING"/>
                    <h:outputScript>
                        createPie('GRAPHIC-ISSUING', 'Check-in por compañía emisora', #{generalDashboardViewBean.issuingCompanyGraphicDataBean.issuingCompanies.values()}, '#{generalDashboardViewBean.issuingCompanyGraphicDataBean.issuingCompanies.keySet()}', false)
                    </h:outputScript>
                </h:panelGroup>
            </p:panel>
            <p:panel id="checkingGraphic" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <div id="GRAPHIC-CHECKING"/>
                    <h:outputScript>
                        createPie('GRAPHIC-CHECKING', 'Compañía de check-in (y porcentaje de sobordo)', #{generalDashboardViewBean.checkingCompanyGraphicDataBean.checkingCompanies.values()}, '#{generalDashboardViewBean.checkingCompanyGraphicDataBean.checkingCompanies.keySet()}', false)
                    </h:outputScript>
                </h:panelGroup>
            </p:panel>
        </p:panelGrid>

        <p:panelGrid columns="4" layout="grid" style="width: 100%; border-radius: 40px; border-width: 2px; border-color: #5A658D">
            <f:facet name="header">
                <h:outputText value="Desglose de tickets por tipo"/>
            </f:facet>
            <p:panel id="totalTickets" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <div id="GRAPHIC-TOTAL-TICKETS"/>
                    <h:outputScript>
                        createPie('GRAPHIC-TOTAL-TICKETS', '', #{generalDashboardViewBean.totalTicketsDataBean.totalTickets.values()}, '#{generalDashboardViewBean.totalTicketsDataBean.totalTickets.keySet()}', true)
                    </h:outputScript>
                </h:panelGroup>
            </p:panel>
            <p:panel id="passengersTickets" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <div id="GRAPHIC-PASSENGERS"/>
                    <h:outputScript>
                        createPie('GRAPHIC-PASSENGERS', '', #{generalDashboardViewBean.passengersTicketsDataBean.passengersType.values()}, '#{generalDashboardViewBean.passengersTicketsDataBean.passengersType.keySet()}', true)
                    </h:outputScript>
                </h:panelGroup>
            </p:panel>
            <p:panel id="vehiclesTickets" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <div id="GRAPHIC-VEHICLES"/>
                    <h:outputScript>
                        createPie('GRAPHIC-VEHICLES', '', #{generalDashboardViewBean.vehiclesTicketsDataBean.vehiclesType.values()}, '#{generalDashboardViewBean.vehiclesTicketsDataBean.vehiclesType.keySet()}', true)
                    </h:outputScript>
                </h:panelGroup>

            </p:panel>
            <p:panel id="Filter" style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                <h:panelGroup rendered="#{generalDashboardViewBean.totalVehiclesAndPassengers != 0}">
                    <h:panelGrid columns="3" style="width: 100%">
                        <h:outputText value=""/>
                        <h:outputText value="Issuing" style="color: #517DBA"/>
                        <h:outputText value="Checking" style="color: #517DBA"/>

                        <h:graphicImage name="images/aml.png" style="display: block; margin: auto"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.issuingCompaniesSelected['AML']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.checkingCompaniesSelected['AML']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>

                        <h:graphicImage name="images/balearia.png" style="display: block; margin: auto"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.issuingCompaniesSelected['BALEARIA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.checkingCompaniesSelected['BALEARIA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>

                        <h:graphicImage name="images/frs.png" style="display: block; margin: auto"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.issuingCompaniesSelected['FRS']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.checkingCompaniesSelected['FRS']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>

                        <h:graphicImage name="images/intershipping.png" style="display: block; margin: auto"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.issuingCompaniesSelected['INTERSHIPPING']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.checkingCompaniesSelected['INTERSHIPPING']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>

                        <h:graphicImage name="images/trasmediterranea.png" style="display: block; margin: auto"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.issuingCompaniesSelected['TRASMEDITERRANEA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.checkingCompaniesSelected['TRASMEDITERRANEA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.filtering()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>

                        <h:outputText value="TODAS" style="display: block; margin: auto; text-align:center;"/>
                        <p:inputSwitch value="#{generalDashboardViewBean.allIssuingFilters}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.activateIssuingFilters()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                        <p:inputSwitch value="#{generalDashboardViewBean.allCheckingFilters}" disabled="#{generalDashboardViewBean.disableFilters}">
                            <p:ajax listener="#{generalDashboardViewBean.activateCheckingFilters()}" update="Filter, :completeView:totalTickets, :completeView:passengersTickets, :completeView:vehiclesTickets"/>
                        </p:inputSwitch>
                    </h:panelGrid>
                </h:panelGroup>
            </p:panel>
        </p:panelGrid>
        <div id="chart"></div>
    </h:form>
</h:body>

</html>

src/main/webapp/pages/salesView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

<h:head>
    <title>Sales View</title>
    <script name="jquery/jquery.js" library="primefaces"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts@latest"></script>
    <script src="../resources/JavaScript/columns.js"></script>

    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>

    <style>

    #chart {
      max-width: 650px;
      margin: 35px auto;
    }

    .ui-panelgrid{
        border-collapse: separate;
        border-spacing: 15px;
    }
    td.vesselColumnColor{
        background-color: #D7DBE7;
    }
    td.departureTimeColumnColor{
        background-color: #D7DBE7;
    }
    td.checkingCompanyColumnColor{
        background-color: 	#E6E6E6;
    }
    .ui-datatable * {
     border : 0px !important;
    }
    .ui-datatable table{
    border-collapse: separate;
    border-spacing: 10px;
    *border-collapse: expression('separate', cellSpacing = '10px');
    }
    .noHeader.ui-datatable table thead tr {
    display: none;
    }
    .ui-widget-header {
        background: #ffffff;
    }
    .ui-datatable-scrollable-theadclone {
        display: none;
    }


</style>
</h:head>

<h:body>
    <h:form id="tableView">
        <h:panelGrid id="main" columns="2" style="margin-bottom:10px; width: 100%; align: center" cellpading="7">
            <h:panelGrid id="total" columns="5" cellpading="7">
                <h:outputText value="Ventas para día: " style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                <p:calendar value="#{salesViewBean.startTime}" pattern="dd/MM/yyyy" />
                <p:commandButton id="dateButton" value="Submit" update=":tableView:table, :tableView:filters, :tableView:boardingTable, :tableView:busesGraphic, :tableView:salesOpenData" action="#{salesViewBean.onTotal}" ajax="true"/>
            </h:panelGrid>
            <h:panelGrid style="margin-bottom:10px; width: 100%; text-align-last: end" cellpading="7">
                <h:outputText value="User: #{loginBean.userHeader}" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; margin-right: 50px" />
            </h:panelGrid>
        </h:panelGrid>

        <hr />

        <p:panelGrid>
            <p:row>
                <p:column style="width: 50%; border-radius: 40px; border-width: 2px; border-color: #5A658D">
                    <h:outputText value="Pasajeros y Vehículos / día" style="display: block; margin: auto; text-align:center; color: #517DBA"/>
                    <h:panelGrid id="table" columns="1" layout="tabular" cellspacing="5px" cellpadding="5px" style="width: 100%">
                        <h:panelGroup>
                            <div id="PASSENGERS-VEHICLES-GRAPHIC"/>
                            <h:outputScript>
                                createColumnsPassengersVehicles('PASSENGERS-VEHICLES-GRAPHIC', '', #{salesViewBean.salesDataBean.passengersData}, #{salesViewBean.salesDataBean.vehiclesData}, #{salesViewBean.salesDataBean.actualDay}, '#{salesViewBean.salesDataBean.daysApplied}', '#{salesViewBean.salesDataBean.threshold1}', '#{salesViewBean.salesDataBean.threshold2}', true)
                            </h:outputScript>
                        </h:panelGroup>
                    </h:panelGrid>
                </p:column>
                
                <p:column rowspan="2" style="vertical-align: top; padding-top: 30px; border-radius: 40px; border-width: 2px; border-color: #5A658D">
                    <h:panelGrid columns="1" layout="grid" style="width: 50%">

                        <h:panelGrid columns="2" id="salesOpenData" style="padding-bottom: 15px;">
                            <h:outputText value="Billetes abiertos pasajeros: " style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                            <h:outputText value="#{salesViewBean.salesOpenData.totalPassengers}" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                            <h:outputText value="Billetes abiertos vehículos: " style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                            <h:outputText value="#{salesViewBean.salesOpenData.totalOtherVehicles}" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                            <h:outputText value="Billetes abiertos: " style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                            <h:outputText value="#{salesViewBean.salesOpenData.totalBus}" style="color: #517DBA; font-family: Verdana,Arial,sans-serif; padding-right:2em"/>
                        </h:panelGrid>

                        <h:outputText value="Naviera" style="color: #517DBA"/>

                        <h:panelGrid columns="12" id="filters" style="margin-top: 10px">
                            <p:selectBooleanCheckbox style="margin-left: 10px" value="#{salesViewBean.companyFilter['AML']}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:graphicImage name="images/aml.png" style="display: block; margin: auto"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.companyFilter['BALEARIA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:graphicImage name="images/balearia.png" style="display: block; margin: auto"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.companyFilter['FRS']}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:graphicImage name="images/frs.png" style="display: block; margin: auto"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.companyFilter['INTERSHIPPING']}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:graphicImage name="images/intershipping.png" style="display: block; margin: auto"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.companyFilter['TRASMEDITERRANEA']}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:graphicImage name="images/trasmediterranea.png" style="display: block; margin: auto"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.allCompanyFilters}" disabled="#{generalDashboardViewBean.disableFilters}">
                                <p:ajax listener="#{salesViewBean.activateCompaniesFilters()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:outputText value="TODAS" style="display: block; margin: auto; text-align:center;"/>
                        </h:panelGrid>

                        <br/>
                        <h:outputText value="Puerto Destino" style="color: #517DBA; margin-top: 20px;"/>
                        <h:panelGrid columns="6" style="margin-top: 10px">
                            <p:selectBooleanCheckbox style="margin-left: 10px" value="#{salesViewBean.arrivalPortFilter['ESCEU']}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:outputText value="Ceuta"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.arrivalPortFilter['MATNG']}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:outputText value="Tánger"/>
                            <p:selectBooleanCheckbox style="margin-left: 15px" value="#{salesViewBean.arrivalPortFilter['MAPTM']}">
                                <p:ajax listener="#{salesViewBean.tableCompanyFilter()}" update="filters, :tableView:boardingTable, :tableView:table, :tableView:busesGraphic, :tableView:salesOpenData"/>
                            </p:selectBooleanCheckbox>
                            <h:outputText value="Tánger Med"/>
                        </h:panelGrid>
                    </h:panelGrid>
                    <br/>
                    <p:separator />
                    <h:outputText value="Embarques" style="display: block; margin: auto; text-align:center; color: #517DBA"/>
                    <br/>
                    <p:dataTable id="boardingTable" var="boarding" value="#{salesViewBean.salesDataBean.boardings}" scrollable="true" scrollHeight="500">
                        <p:column styleClass="vesselColumnColor" headerText="Compañía" style="width: 50%">
                            <h:outputText value="#{boarding.company}"/>
                        </p:column>
                        <p:column styleClass="departureTimeColumnColor" headerText="Fecha" style="width: 20%">
                            <h:outputText value="#{boarding.departureTime}"/>
                        </p:column>
                        <p:column styleClass="checkingCompanyColumnColor" headerText="Per." style="width: 10%">
                            <h:outputText value="#{boarding.passengers}"/>
                        </p:column>
                        <p:column styleClass="checkingCompanyColumnColor" headerText="Veh." style="width: 10%">
                            <h:outputText value="#{boarding.vehicles}"/>
                        </p:column>
                        <p:column styleClass="checkingCompanyColumnColor" headerText="Bus" style="width: 10%">
                            <h:outputText value="#{boarding.buses}"/>
                        </p:column>
                    </p:dataTable>
                </p:column>
            </p:row>
            <p:row>
                <p:column style="border-radius: 40px; border-width: 2px; border-color: #5A658D">
                    <h:outputText value="Autobuses / día" style="display: block; margin: auto; text-align:center; color: #517DBA"/>
                    <h:panelGrid id="busesGraphic" columns="1" layout="tabular" cellspacing="5px" cellpadding="5px" style="width: 100%">
                        <h:panelGroup>
                            <div id="BUSES-GRAPHIC"/>
                            <h:outputScript>
                                createColumnsBuses('BUSES-GRAPHIC', '', #{salesViewBean.salesDataBean.busesData}, '#{salesViewBean.salesDataBean.daysApplied}', #{salesViewBean.salesDataBean.actualDay}, '#{salesViewBean.salesDataBean.threshold1}', '#{salesViewBean.salesDataBean.threshold2}', true)
                            </h:outputScript>
                        </h:panelGroup>
                    </h:panelGrid>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</h:body>



</html>